name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  message:
    required: true
    description: 'The message'
    default: 'Hello world'
outputs:
  greeting:
    description: 'The greeting'
runs:
  using: 'node12'
  main: 'dist/index.js'
